# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c94a00a41bb96d790837eefa23a2a2b6c0255f77b027befb66cc17a4dcbad1d425464276a5d2bc9adab6fc4dc92164eb55630fa00cabc09c94c195e6ea1ea031

test:
  secret_key_base: 350e4bea7114d1f85e868605aab6014c1207a55d9850a462d1a3aa4222c9cea2164c12fee1ad61f29c6a7a428231a71760ccfe50ee11ee7c285369dd7661c59c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
